version: "3.3"
services:
  bootstrapper:
    image: need:1.1
    command: ["-s", "122d92ad-065c-49d6-b502-ea2bc30f584c"]
    deploy:
      mode: global
    environment:
      NEED_UUID: '122d92ad-065c-49d6-b502-ea2bc30f584c'
    labels:
      boot122d92ad-065c-49d6-b502-ea2bc30f584c: "true"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    configs:
      - source: topology
        target: /topology.xml
        uid: '0'
        gid: '0'
        mode: 0555
    networks:
      - NEEDnet

  dashboard-122d92ad-065c-49d6-b502-ea2bc30f584c:
    image: warpenguin.no-ip.org/dashboard:1.0
    ports:
      - "8088:8088"
    hostname: dashboard
    deploy:
      replicas: 1
    environment:
      NEED_UUID: '122d92ad-065c-49d6-b502-ea2bc30f584c'
    configs:
      - source: topology
        target: /topology.xml
        uid: '0'
        gid: '0'
        mode: 0555
    networks:
      - NEEDnet
      - outside

  logger-122d92ad-065c-49d6-b502-ea2bc30f584c:
    image: warpenguin.no-ip.org/logger:1.0
    hostname: logger
    deploy:
      replicas: 1
    environment:
      NEED_UUID: '122d92ad-065c-49d6-b502-ea2bc30f584c'
    configs:
      - source: topology
        target: /topology.xml
        uid: '0'
        gid: '0'
        mode: 0555
    networks:
      - NEEDnet
      - outside

  client1-122d92ad-065c-49d6-b502-ea2bc30f584c:
    image: warpenguin.no-ip.org/alpineclient:1.0
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/NEED_hang; exec /bin/sh <> /tmp/NEED_hang #"]
    command: ['server', '0', '0']
    hostname: client1
    labels:
      122d92ad-065c-49d6-b502-ea2bc30f584c: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      NEED_UUID: '122d92ad-065c-49d6-b502-ea2bc30f584c'
    networks:
      - NEEDnet

  client2-122d92ad-065c-49d6-b502-ea2bc30f584c:
    image: warpenguin.no-ip.org/alpineclient:1.0
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/NEED_hang; exec /bin/sh <> /tmp/NEED_hang #"]
    command: ['server', '0', '0']
    hostname: client2
    labels:
      122d92ad-065c-49d6-b502-ea2bc30f584c: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      NEED_UUID: '122d92ad-065c-49d6-b502-ea2bc30f584c'
    networks:
      - NEEDnet

  client3-122d92ad-065c-49d6-b502-ea2bc30f584c:
    image: warpenguin.no-ip.org/alpineclient:1.0
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/NEED_hang; exec /bin/sh <> /tmp/NEED_hang #"]
    command: ['server', '0', '0']
    hostname: client3
    labels:
      122d92ad-065c-49d6-b502-ea2bc30f584c: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      NEED_UUID: '122d92ad-065c-49d6-b502-ea2bc30f584c'
    networks:
      - NEEDnet

  server-122d92ad-065c-49d6-b502-ea2bc30f584c:
    image: warpenguin.no-ip.org/alpineserver:1.0
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/NEED_hang; exec /bin/sh <> /tmp/NEED_hang #"]
    hostname: server
    labels:
      122d92ad-065c-49d6-b502-ea2bc30f584c: "true"
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
    environment:
      NEED_UUID: '122d92ad-065c-49d6-b502-ea2bc30f584c'
    networks:
      - NEEDnet

configs:
  topology:
    file: topology5.xml

networks:
  NEEDnet:
    external:
      name: test_overlay
  outside:
    driver: overlay

